name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-node-template-fuzzers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup dependencies
        run: |
          cargo install ziggy cargo-afl honggfuzz grcov
          rustup target add wasm32-unknown-unknown
      - name: Build fuzzer
        run: |
          cargo afl config --build --firce
          cargo ziggy build
